require "card_group/high_card"
require "card_group/n_of_a_kind"
require "card_group/two_pair"
require "card_group/straight"
require "card_group/flush"
require "card_group/full_house"
require "card_group/straight_flush"
